/**
 * @module parser/interpreter
 *
 * AST interpreter. Takes a node and a scope and returns the value.
 *
 * Security: there is no implicit access to `window`, `globalThis`, `document`,
 * `fetch` or `eval`. Identifiers not in scope are looked up in a closed list of
 * allowed globals, configurable by the application.
 */

import type { Node } from './parser';

/** Minimum contract that a scope must fulfill to be evaluated. */
export interface EvalScope {
  /** Returns the object containing the key, walking up the scope chain. */
  lookup(name: string): Record<string, any> | undefined;
  /** Reads a value from the scope chain. */
  get(name: string): unknown;
  /** Writes to the scope chain, in the key owner when it exists. */
  set(name: string, value: unknown): void;
  /** Creates a child scope with local variables, used by arrow functions and `v-for`. */
  child(vars: Record<string, unknown>): EvalScope;
}

/**
 * Globals allowed within template expressions.
 *
 * Extend with `V.config.globals.Minha = valor`.
 */
/**
 * Safe subset of `Object`.
 *
 * The native `Object` cannot be fully exposed. Key blocking covers direct
 * access like `x.constructor`, but the reflective methods of `Object` itself
 * receive the target as an ARGUMENT, and arguments don't pass through that
 * blocking. The chain below would return `Function` and execute arbitrary code:
 *
 * ```js
 * Object.getOwnPropertyDescriptor(Object.getPrototypeOf(Object), 'constructor')
 *   .value('return this')()
 * ```
 *
 * The rule that closes this once and for all is not an ever-growing list of
 * prohibitions: it's inverting the pattern. A template expression can CALL
 * functionality; it doesn't receive tools to inspect the JavaScript runtime.
 * For this reason `getPrototypeOf`, `setPrototypeOf`,
 * `getOwnPropertyDescriptor`, `getOwnPropertyDescriptors`,
 * `getOwnPropertyNames`, `getOwnPropertySymbols`, `defineProperty`,
 * `defineProperties` and `create` are excluded.
 */
const SafeObject = /* @__PURE__ */ Object.freeze({
  keys: Object.keys,
  values: Object.values,
  entries: Object.entries,
  fromEntries: Object.fromEntries,
  assign: Object.assign,
  is: Object.is,
  hasOwn:
    (Object as unknown as { hasOwn?: (o: object, k: PropertyKey) => boolean }).hasOwn ??
    ((o: object, k: PropertyKey): boolean => Object.prototype.hasOwnProperty.call(o, k)),
});

/**
 * Names the sandbox refuses on purpose.
 *
 * They exist only to shape the error message: nothing here is reachable either
 * way. The point is not to answer "it was not found, expose it with
 * V.config.globals" for a name nobody should be exposing, which would be
 * instructions for undoing the sandbox.
 */
const DELIBERATELY_WITHHELD = /* @__PURE__ */ new Set([
  'eval',
  'Function',
  'window',
  'globalThis',
  'self',
  'top',
  'parent',
  'document',
  'fetch',
  'XMLHttpRequest',
  'importScripts',
  'require',
  'process',
  'Reflect',
  'Proxy',
  'WebAssembly',
  'localStorage',
  'sessionStorage',
  'indexedDB',
  'navigator',
  'location',
  'history',
  'crypto',
  'Worker',
  'SharedWorker',
  'ServiceWorker',
]);

export const allowedGlobals: Record<string, unknown> = {
  Math,
  JSON,
  Date,
  Number,
  String,
  Boolean,
  Array,
  Object: SafeObject,
  Intl,
  RegExp,
  Promise,
  parseInt,
  parseFloat,
  isNaN,
  isFinite,
  encodeURIComponent,
  decodeURIComponent,
  console,
};

/** Runtime error for an expression, with original text attached. */
export class VoodooRuntimeError extends Error {
  constructor(
    message: string,
    public readonly expression?: string
  ) {
    super(expression ? `${message}\n\nExpression: ${expression}` : message);
    this.name = 'VoodooRuntimeError';
  }
}

const SPREAD = Symbol('spread');

/**
 * Keys that open the prototype chain and are thus outside the reach of
 * template expressions.
 *
 * Reading `constructor` was enough to escape the interpreter: `({}).constructor`
 * returns `Object`, and `Object.constructor` returns `Function`, that is
 * `constructor.constructor("return this")()` was `eval` through the back door,
 * with access to `window`, `document` and `fetch`. Writing to `__proto__` or
 * `prototype` pollutes `Object.prototype` and contaminates the entire page.
 */
const BLOCKED_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

/** `true` when the key reaches the prototype chain. */
export function chaveBloqueada(key: unknown): boolean {
  return typeof key === 'string' && BLOCKED_KEYS.has(key);
}

/** Rejects the key when it reaches the prototype chain. */
function checkKey(key: unknown, expression?: string): PropertyKey {
  if (chaveBloqueada(key)) {
    throw new VoodooRuntimeError(
      `Access blocked to "${String(key)}": template expressions cannot reach ` +
        'the prototype chain. Expose a method in state instead.',
      expression
    );
  }
  return key as PropertyKey;
}

/**
 * Evaluates an AST node.
 *
 * @param node node generated by `parse()`
 * @param scope read and write scope
 */
export function evaluate(node: Node, scope: EvalScope): any {
  switch (node.t) {
    case 'lit':
      return node.v;

    case 'tpl': {
      let out = node.quasis[0] ?? '';
      for (let i = 0; i < node.exprs.length; i++) {
        out += stringify(evaluate(node.exprs[i], scope));
        out += node.quasis[i + 1] ?? '';
      }
      return out;
    }

    case 'id': {
      // `constructor` and friends exist on any object by inheritance, so
      // `name in data` would find them even without anything declared.
      checkKey(node.n);
      const owner = scope.lookup(node.n);
      if (owner) return owner[node.n];
      if (node.n in allowedGlobals) return allowedGlobals[node.n];
      return undefined;
    }

    case 'member': {
      const obj = evaluate(node.o, scope);
      if (obj == null) {
        if (node.opt) return undefined;
        throw new VoodooRuntimeError(
          `Could not read "${describeKey(node, scope)}" from ${obj === null ? 'null' : 'undefined'}`
        );
      }
      const key = checkKey(
        node.computed ? evaluate(node.p, scope) : (node.p as { v: string }).v
      );
      return (obj as any)[key];
    }

    case 'call': {
      let thisArg: unknown;
      let fn: unknown;

      if (node.callee.t === 'member') {
        const obj = evaluate(node.callee.o, scope);
        if (obj == null) {
          if (node.callee.opt || node.opt) return undefined;
          throw new VoodooRuntimeError(
            `Could not call "${describeKey(node.callee, scope)}" from ${
              obj === null ? 'null' : 'undefined'
            }`
          );
        }
        const key = checkKey(
          node.callee.computed
            ? evaluate(node.callee.p, scope)
            : (node.callee.p as { v: string }).v
        );
        thisArg = obj;
        fn = (obj as any)[key];
      } else if (node.callee.t === 'id') {
        checkKey(node.callee.n);
        const owner = scope.lookup(node.callee.n);
        if (owner) {
          thisArg = owner;
          fn = owner[node.callee.n];
        } else {
          fn = allowedGlobals[node.callee.n];
        }
      } else {
        fn = evaluate(node.callee, scope);
      }

      if (fn == null && node.opt) return undefined;
      if (typeof fn !== 'function') {
        const name = node.callee.t === 'id' ? node.callee.n : describeKey(node.callee, scope);

        // A bare name that resolves nowhere is almost always a global the page
        // defined and never exposed, not a typo. Saying "is not a function"
        // sends people hunting for a bug in their own code, when the answer is
        // that expressions cannot reach `window` by design and the name has to
        // be handed over explicitly.
        if (node.callee.t === 'id' && !scope.lookup(name) && !(name in allowedGlobals)) {
          // Except for the names that are withheld on purpose. Telling someone
          // how to hand `eval` to a template would be advice that undoes the
          // sandbox, so those get told they are blocked and nothing else.
          if (DELIBERATELY_WITHHELD.has(name)) {
            throw new VoodooRuntimeError(
              `"${name}" is blocked. Expressions run in a sandbox without access to it.`
            );
          }
          throw new VoodooRuntimeError(
            `"${name}" was not found. Expressions cannot reach window: expose it with ` +
              `V.config.globals.${name} = ..., or put it in scope with V.data({ ${name} }).`
          );
        }

        throw new VoodooRuntimeError(`"${name}" is not a function`);
      }

      return (fn as Function).apply(thisArg, evalArgs(node.args, scope));
    }

    case 'unary': {
      if (node.op === '...') return { [SPREAD]: evaluate(node.a, scope) };
      if (node.op === 'typeof') {
        // typeof of unknown identifier cannot throw error.
        if (node.a.t === 'id') {
          // Blocked key never leaks, not even through `typeof`.
          if (chaveBloqueada(node.a.n)) return 'undefined';
          const owner = scope.lookup(node.a.n);
          const value = owner ? owner[node.a.n] : allowedGlobals[node.a.n];
          return typeof value;
        }
        return typeof evaluate(node.a, scope);
      }
      const v = evaluate(node.a, scope);
      switch (node.op) {
        case '!':
          return !v;
        case '-':
          return -(v as number);
        case '+':
          return +(v as number);
        case 'void':
          return undefined;
      }
      throw new VoodooRuntimeError(`Unsupported unary operator: ${node.op}`);
    }

    case 'update': {
      const old = Number(evaluate(node.a, scope));
      const updated = node.op === '++' ? old + 1 : old - 1;
      assign(node.a, updated, scope);
      return node.prefix ? updated : old;
    }

    case 'bin': {
      const l = evaluate(node.l, scope);
      const r = evaluate(node.r, scope);
      switch (node.op) {
        case '+':
          return (l as number) + (r as number);
        case '-':
          return (l as number) - (r as number);
        case '*':
          return (l as number) * (r as number);
        case '/':
          return (l as number) / (r as number);
        case '%':
          return (l as number) % (r as number);
        case '**':
          return (l as number) ** (r as number);
        case '==':
          // eslint-disable-next-line eqeqeq
          return l == r;
        case '!=':
          // eslint-disable-next-line eqeqeq
          return l != r;
        case '===':
          return l === r;
        case '!==':
          return l !== r;
        case '<':
          return (l as number) < (r as number);
        case '>':
          return (l as number) > (r as number);
        case '<=':
          return (l as number) <= (r as number);
        case '>=':
          return (l as number) >= (r as number);
        case 'in':
          return (l as PropertyKey) in (r as object);
        case 'instanceof':
          return l instanceof (r as Function);
      }
      throw new VoodooRuntimeError(`Unsupported operator: ${node.op}`);
    }

    case 'logic': {
      const l = evaluate(node.l, scope);
      if (node.op === '&&') return l ? evaluate(node.r, scope) : l;
      if (node.op === '||') return l ? l : evaluate(node.r, scope);
      return l ?? evaluate(node.r, scope);
    }

    case 'cond':
      return evaluate(node.test, scope) ? evaluate(node.cons, scope) : evaluate(node.alt, scope);

    case 'assign': {
      let value: unknown;
      if (node.op === '=') {
        value = evaluate(node.value, scope);
      } else if (node.op === '&&=' || node.op === '||=' || node.op === '??=') {
        const current = evaluate(node.target, scope);
        const shouldAssign =
          node.op === '&&=' ? !!current : node.op === '||=' ? !current : current == null;
        if (!shouldAssign) return current;
        value = evaluate(node.value, scope);
      } else {
        const current = evaluate(node.target, scope) as any;
        const operand = evaluate(node.value, scope) as any;
        switch (node.op) {
          case '+=':
            value = current + operand;
            break;
          case '-=':
            value = current - operand;
            break;
          case '*=':
            value = current * operand;
            break;
          case '/=':
            value = current / operand;
            break;
          case '%=':
            value = current % operand;
            break;
          case '**=':
            value = current ** operand;
            break;
          default:
            throw new VoodooRuntimeError(`Unsupported assignment: ${node.op}`);
        }
      }
      assign(node.target, value, scope);
      return value;
    }

    case 'arrow': {
      const params = node.params;
      const body = node.body;
      return (...args: unknown[]) => {
        const vars: Record<string, unknown> = {};
        for (let i = 0; i < params.length; i++) vars[params[i]] = args[i];
        return evaluate(body, scope.child(vars));
      };
    }

    case 'obj': {
      const out: Record<string, unknown> = {};
      for (const prop of node.props) {
        if (prop.spread) {
          Object.assign(out, evaluate(prop.spread, scope) as object);
        } else {
          // `{ __proto__: ... }` would change the prototype of the object created here.
          const key = checkKey(
            prop.key !== null ? prop.key : String(evaluate(prop.keyExpr!, scope))
          ) as string;
          out[key] = evaluate(prop.value!, scope);
        }
      }
      return out;
    }

    case 'arr': {
      const out: unknown[] = [];
      for (const el of node.els) {
        if (el && typeof el === 'object' && 'spread' in el) {
          out.push(...(evaluate(el.spread, scope) as unknown[]));
        } else {
          out.push(evaluate(el as Node, scope));
        }
      }
      return out;
    }

    case 'seq': {
      let last: unknown;
      for (const stmt of node.body) last = evaluate(stmt, scope);
      return last;
    }
  }

  throw new VoodooRuntimeError(`Unknown node: ${(node as { t: string }).t}`);
}

function evalArgs(args: Node[], scope: EvalScope): unknown[] {
  const out: unknown[] = [];
  for (const arg of args) {
    const value = evaluate(arg, scope);
    if (value && typeof value === 'object' && SPREAD in (value as object)) {
      out.push(...((value as any)[SPREAD] as unknown[]));
    } else {
      out.push(value);
    }
  }
  return out;
}

/** Writes to an identifier or member access. */
function assign(target: Node, value: unknown, scope: EvalScope): void {
  if (target.t === 'id') {
    checkKey(target.n);
    scope.set(target.n, value);
    return;
  }
  if (target.t === 'member') {
    const obj = evaluate(target.o, scope);
    if (obj == null) {
      throw new VoodooRuntimeError('Could not write to null or undefined');
    }
    // `x.__proto__.qualquer = 1` would pollute `Object.prototype` for the entire page.
    const key = checkKey(
      target.computed ? evaluate(target.p, scope) : (target.p as { v: string }).v
    );
    (obj as any)[key] = value;
    return;
  }
  throw new VoodooRuntimeError('Invalid assignment target');
}

function describeKey(node: Node, scope: EvalScope): string {
  if (node.t === 'member') {
    return node.computed ? String(evaluate(node.p, scope)) : String((node.p as { v: string }).v);
  }
  if (node.t === 'id') return node.n;
  return 'value';
}

/** Converts any value to text that will be written to the DOM. */
export function stringify(value: unknown): string {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (value instanceof Date) return value.toLocaleString();
  if (typeof value === 'object') {
    try {
      return JSON.stringify(value);
    } catch {
      return String(value);
    }
  }
  return String(value);
}
