/**
 * Fuzz / property-based testing of the parser.
 *
 * The parser is a security boundary: Voodoo doesn't use `eval` or
 * `new Function`, so all attribute text passes through lexer -> parser ->
 * interpreter. A unit test covers what someone remembered to write;
 * this file covers what nobody remembered.
 *
 * The idea is not to compare values, but to verify PROPERTIES that must
 * hold for any input:
 *
 *   1. `parse()` always terminates (no infinite loops).
 *   2. Deep nesting terminates with predictable error, never raw `RangeError`
 *      from stack overflow.
 *   3. Invalid input always throws `VoodooSyntaxError`, never `TypeError`
 *      or other generic JavaScript error.
 *   4. The cache is idempotent, even on `MAX_CACHE` overflow.
 *   5. Round-trip: valid expression from safe subset evaluates without throwing.
 *
 * Everything is deterministic. The seed is fixed, the generator is mulberry32,
 * and there's no `Math.random` anywhere: a failure always reproduces the same way.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { parse, clearParseCache } from '../src/parser/parser';
import { tokenize, VoodooSyntaxError } from '../src/parser/lexer';
import { evaluate } from '../src/parser/interpreter';
import { Scope } from '../src/runtime/scope';
import { reactive } from '../src/reactivity';
import {
  Random,
  hugeCases,
  edgeCases,
  controlledData,
  generateSafeExpression,
  generateValidExpression,
  generateProgram,
  mutate,
} from './helpers/gerador-expressoes';

/** Fixed seed. Changing this number changes the entire corpus. */
const SEED = 0xc0ffee;

/** Time ceiling per expression. A short expression exceeding this is a defect. */
const LIMIT_MS = 1000;

/** Ceiling for huge inputs, which legitimately cost more. */
const LIMIT_MS_HUGE = 4000;

interface Violation {
  source: string;
  reason: string;
}

function summary(source: string): string {
  const short = source.length > 80 ? `${source.slice(0, 80)}… (${source.length} chars)` : source;
  return JSON.stringify(short);
}

/**
 * Analyzes an expression and returns the contract violation, if any.
 *
 * Contract: either `parse` returns an AST or throws `VoodooSyntaxError`.
 * Any other error (`TypeError`, `RangeError`, bare string) is a bug.
 * Exceeding time limit is also a bug.
 */
function verifyContract(source: string, limitMs = LIMIT_MS): Violation | null {
  const start = Date.now();
  let node: unknown;
  let error: unknown;
  try {
    node = parse(source);
  } catch (err) {
    error = err;
  }
  const spent = Date.now() - start;

  if (spent > limitMs) {
    return { source, reason: `took ${spent}ms (limit ${limitMs}ms)` };
  }
  if (error !== undefined) {
    if (!(error instanceof VoodooSyntaxError)) {
      const name = error instanceof Error ? `${error.name}: ${error.message.split('\n')[0]}` : typeof error;
      return { source, reason: `threw ${name} instead of VoodooSyntaxError` };
    }
    if (!error.message || error.message.length === 0) {
      return { source, reason: 'VoodooSyntaxError without message' };
    }
    return null;
  }
  if (typeof node !== 'object' || node === null || typeof (node as { t?: unknown }).t !== 'string') {
    return { source, reason: `returned invalid AST: ${String(node)}` };
  }
  return null;
}

function report(violations: Violation[]): void {
  if (violations.length === 0) return;
  const list = violations
    .slice(0, 10)
    .map((v) => ` - ${summary(v.source)} => ${v.reason}`)
    .join('\n');
  throw new Error(`${violations.length} input(s) broke parser contract:\n${list}`);
}

beforeEach(() => {
  clearParseCache();
});

// ---------------------------------------------------------------------------
// 1 and 3: always terminates, error is always VoodooSyntaxError
// ---------------------------------------------------------------------------

describe('fuzz: parser terminates and errors predictably', () => {
  it('2000 expressions generated by grammar', () => {
    const r = new Random(SEED);
    const violations: Violation[] = [];
    for (let i = 0; i < 2000; i++) {
      const source = generateValidExpression(r, 1 + r.integer(5));
      const v = verifyContract(source);
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('500 programs with multiple expressions separated by ;', () => {
    const r = new Random(SEED ^ 0x5eed);
    const violations: Violation[] = [];
    for (let i = 0; i < 500; i++) {
      const v = verifyContract(generateProgram(r, 1 + r.integer(4)));
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('3000 destructive mutations of valid expressions', () => {
    const r = new Random(SEED ^ 0xbadc0de);
    const violations: Violation[] = [];
    for (let i = 0; i < 3000; i++) {
      let source = generateValidExpression(r, 1 + r.integer(4));
      const rounds = 1 + r.integer(3);
      for (let m = 0; m < rounds; m++) source = mutate(r, source);
      const v = verifyContract(source);
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('1000 random sequences of punctuation characters', () => {
    const r = new Random(SEED ^ 0x1234);
    const alphabet = `()[]{}<>+-*/%!?:;.,'"\`\\|&^~=$_ \n\t0123456789abz😀áΩ`;
    const violations: Violation[] = [];
    for (let i = 0; i < 1000; i++) {
      const n = 1 + r.integer(40);
      let source = '';
      for (let c = 0; c < n; c++) source += alphabet[r.integer(alphabet.length)];
      const v = verifyContract(source);
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('hand-written edge cases', () => {
    const violations: Violation[] = [];
    for (const source of edgeCases()) {
      const v = verifyContract(source);
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('huge inputs complete within budget', () => {
    const violations: Violation[] = [];
    for (const source of hugeCases()) {
      const v = verifyContract(source, LIMIT_MS_HUGE);
      if (v) violations.push(v);
    }
    report(violations);
  });

  it('lexer alone obeys the same contract', () => {
    const r = new Random(SEED ^ 0xfeed);
    const violations: Violation[] = [];
    const corpus = [...edgeCases()];
    for (let i = 0; i < 500; i++) corpus.push(mutate(r, generateValidExpression(r, 3)));
    for (const source of corpus) {
      try {
        tokenize(source);
      } catch (err) {
        if (!(err instanceof VoodooSyntaxError)) {
          violations.push({
            source,
            reason: `tokenize threw ${err instanceof Error ? err.name : typeof err}`,
          });
        }
      }
    }
    report(violations);
  });
});

// ---------------------------------------------------------------------------
// 2: deep nesting (regressions found by fuzz)
// ---------------------------------------------------------------------------

describe('fuzz: deep nesting does not overflow the stack', () => {
  // BUG FOUND BY FUZZ: `((((...))))` with thousands of levels leaked
  // `RangeError: Maximum call stack size exceeded`, raw engine error,
  // instead of Voodoo syntax error. Fixed with MAX_DEPTH limit in src/parser/parser.ts.
  const deep: Array<[string, string]> = [
    ['parentheses', `${'('.repeat(5000)}1${')'.repeat(5000)}`],
    ['arrays', `${'['.repeat(5000)}${']'.repeat(5000)}`],
    ['objects', `${'{a:'.repeat(5000)}1${'}'.repeat(5000)}`],
    ['unary', `${'!'.repeat(20000)}1`],
    ['ternary', `${'a?1:'.repeat(20000)}2`],
    ['arrows', `${'x=>'.repeat(20000)}1`],
    ['exponentiation', `${'2**'.repeat(20000)}2`],
    ['calls', `f${'('.repeat(5000)}1${')'.repeat(5000)}`],
    ['templates', `${'`${'.repeat(5000)}1${'}`'.repeat(5000)}`],
    ['spreads', `[${'...['.repeat(5000)}1${']'.repeat(5000)}]`],
  ];

  for (const [name, source] of deep) {
    it(`${name} nested thousands of times become VoodooSyntaxError`, () => {
      let error: unknown;
      try {
        parse(source);
      } catch (err) {
        error = err;
      }
      expect(error).toBeInstanceOf(VoodooSyntaxError);
      expect(String((error as Error).message)).toMatch(/nested/i);
    });
  }

  it('300 levels of parentheses remain valid', () => {
    // The limit exists to contain absurdity, not to constrain real usage.
    const source = `${'('.repeat(300)}1${')'.repeat(300)}`;
    expect(parse(source)).toEqual({ t: 'lit', v: 1 });
  });

  it('truly nested template continues working', () => {
    expect(() => parse('`${`${`${a}`}`}`')).not.toThrow();
  });

  it('long but shallow chain does not hit limit', () => {
    const sum = Array.from({ length: 5000 }, () => '1').join(' + ');
    expect(() => parse(sum)).not.toThrow();
    expect(() => parse(`a${'.b'.repeat(5000)}`)).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// 3: specific bugs found by fuzz in lexer escapes
// ---------------------------------------------------------------------------

describe('invalid escapes in string are syntax error, not RangeError', () => {
  // BUG FOUND BY FUZZ: `String.fromCodePoint` throws raw `RangeError`
  // for NaN and values above 0x10FFFF, and the lexer didn't validate anything.
  const cases = [
    '"\\u{ZZ}"',
    '"\\u{}"',
    '"\\u{110000}"',
    '"\\u{FFFFFFFF}"',
    '"\\u{-1}"',
    '"\\uZZZZ"',
    '"\\u41"',
    '"\\xZZ"',
    '"\\x4"',
  ];
  for (const source of cases) {
    it(`rejects ${source}`, () => {
      expect(() => parse(source)).toThrow(VoodooSyntaxError);
    });
  }

  // BUG FOUND BY FUZZ: without the `}`, `indexOf` returned -1 and the lexer
  // did `i = close + 1`, moving the cursor back to source start and
  // reanalyzing everything with wrong positions.
  it('unicode escape without closing brace does not rewind cursor', () => {
    let error: VoodooSyntaxError | undefined;
    try {
      tokenize('+"\\u{41ZZZ');
    } catch (err) {
      error = err as VoodooSyntaxError;
    }
    expect(error).toBeInstanceOf(VoodooSyntaxError);
    expect(error!.message).toContain('Unclosed');
    // Position points to the string, not the start of the expression.
    expect(error!.position).toBe(1);
  });

  // Fuzz generated `++null` (two `+` stuck together) and showed that the parser
  // accepts increment on literal: the AST comes out and only the interpreter
  // complains with VoodooRuntimeError. JavaScript rejects this at parse time,
  // and the parser already rejects `1 = 2` with "Invalid assignment target".
  // Missing the same check in `++`/`--`. Didn't touch it now because it changes
  // when the error occurs (parsing vs evaluation) and the interpreter is being
  // edited in parallel; the current error is still typed, so no raw error leak.
  it.todo('++ and -- on literal should be rejected at parse time');

  it('valid escapes continue working', () => {
    expect(parse('"\\u0041"')).toEqual({ t: 'lit', v: 'A' });
    expect(parse('"\\u{1F600}"')).toEqual({ t: 'lit', v: '😀' });
    expect(parse('"\\x41"')).toEqual({ t: 'lit', v: 'A' });
    expect(parse('"\\n\\t\\\\"')).toEqual({ t: 'lit', v: '\n\t\\' });
  });
});

// ---------------------------------------------------------------------------
// 4: cache idempotence
// ---------------------------------------------------------------------------

describe('fuzz: cache is idempotent', () => {
  it('parsing twice returns same AST for 800 expressions', () => {
    const r = new Random(SEED ^ 0xcafe);
    for (let i = 0; i < 800; i++) {
      const source = generateValidExpression(r, 1 + r.integer(4));
      let first: unknown;
      try {
        first = parse(source);
      } catch {
        // Invalid input: must remain invalid on second call.
        expect(() => parse(source)).toThrow(VoodooSyntaxError);
        continue;
      }
      const second = parse(source);
      expect(second).toBe(first);
      expect(second).toEqual(first);
    }
  });

  it('MAX_CACHE overflow does not change result of any expression', () => {
    const reference = parse('a.b + c');
    const copy = JSON.parse(JSON.stringify(reference));
    // MAX_CACHE is 2000; 2600 distinct expressions force cleanup.
    for (let i = 0; i < 2600; i++) parse(`v${i} + ${i}`);
    const after = parse('a.b + c');
    expect(JSON.parse(JSON.stringify(after))).toEqual(copy);
    expect(parse('v0 + 0')).toEqual(parse('v0 + 0'));
  });

  it('cached AST is not shared between different sources', () => {
    expect(parse('a + b')).not.toBe(parse('a + c'));
  });

  it('syntax error does not enter cache', () => {
    expect(() => parse('a +')).toThrow(VoodooSyntaxError);
    expect(() => parse('a +')).toThrow(VoodooSyntaxError);
  });
});

// ---------------------------------------------------------------------------
// 5: round-trip with evaluation
// ---------------------------------------------------------------------------

describe('fuzz: round-trip parse + evaluation', () => {
  it('1000 expressions from safe subset evaluate without throwing', () => {
    const r = new Random(SEED ^ 0xa11ce);
    const violations: Violation[] = [];
    for (let i = 0; i < 1000; i++) {
      const source = generateSafeExpression(r, 1 + r.integer(4));
      const scope = new Scope(reactive(controlledData()));
      try {
        const value = evaluate(parse(source), scope);
        // Evaluate again with fresh scope must give same type.
        const other = evaluate(parse(source), new Scope(reactive(controlledData())));
        if (typeof value !== typeof other) {
          violations.push({ source, reason: `unstable type: ${typeof value} vs ${typeof other}` });
        }
      } catch (err) {
        violations.push({
          source,
          reason: `evaluation threw ${err instanceof Error ? `${err.name}: ${err.message.split('\n')[0]}` : typeof err}`,
        });
      }
    }
    report(violations);
  });

  it('evaluating any generated expression only throws true Error', () => {
    const r = new Random(SEED ^ 0xf00d);
    const violations: Violation[] = [];
    for (let i = 0; i < 800; i++) {
      const source = generateValidExpression(r, 1 + r.integer(4));
      const scope = new Scope(reactive(controlledData()));
      try {
        evaluate(parse(source), scope);
      } catch (err) {
        if (!(err instanceof Error)) {
          violations.push({ source, reason: `threw non-Error: ${typeof err}` });
        }
      }
    }
    report(violations);
  });
});
