/**
 * Generates the documentation search index.
 *
 *   node scripts/docs-index.mjs
 *
 * Reads all pages from site/docs, breaks each one into sections marked by
 * <h2 id> and <h3 id>, and writes site/docs/assets/busca.js with the array that the
 * search field loads on demand.
 *
 * Format of each item, short on purpose because the file goes to the
 * browser:
 *
 *   t  page title
 *   s  section title, empty at page opening
 *   e  text snippet, up to 220 characters
 *   p  page id, in the same format as the menu
 *   a  section anchor, empty at opening
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const RAIZ = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(RAIZ, 'site', 'docs');
const SAIDA = join(DOCS, 'assets', 'busca.js');

const LIMITE_TRECHO = 220;

/** Pages in menu order, read from docs.js itself to avoid duplicating the list. */
function paginasDoMenu() {
  const fonte = readFileSync(join(DOCS, 'assets', 'docs.js'), 'utf8');
  const ids = [];
  const re = /\{\s*id:\s*'([^']*)'\s*,\s*titulo:\s*'((?:[^'\\]|\\.)*)'/g;
  let achado;
  while ((achado = re.exec(fonte)) !== null) {
    ids.push({ id: achado[1], titulo: achado[2].replace(/\\'/g, "'") });
  }
  return ids;
}

function caminhoDaPagina(id) {
  return join(DOCS, id ? `${id}.html` : 'index.html');
}

/** Body of the <article>, which is the only indexable part. */
function artigoDe(html) {
  const inicio = html.indexOf('<article');
  const fim = html.indexOf('</article>');
  if (inicio < 0 || fim < 0) return '';
  return html.slice(html.indexOf('>', inicio) + 1, fim);
}

function semTags(trecho) {
  return trecho
    .replace(/<pre[\s\S]*?<\/pre>/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

function encurtar(texto) {
  if (texto.length <= LIMITE_TRECHO) return texto;
  const corte = texto.slice(0, LIMITE_TRECHO);
  const espaco = corte.lastIndexOf(' ');
  return `${corte.slice(0, espaco > 120 ? espaco : LIMITE_TRECHO)}...`;
}

/** Breaks the article into opening plus one entry per heading with id. */
function secoesDe(artigo) {
  const partes = [];
  const re = /<h([23])\s+id="([^"]+)"[^>]*>([\s\S]*?)<\/h\1>/g;

  let ultimoFim = 0;
  let anterior = null;
  let achado;

  while ((achado = re.exec(artigo)) !== null) {
    const corpo = artigo.slice(ultimoFim, achado.index);
    if (anterior) anterior.texto = semTags(corpo);
    else partes.push({ ancora: '', secao: '', texto: semTags(corpo) });

    anterior = { ancora: achado[2], secao: semTags(achado[3]), texto: '' };
    partes.push(anterior);
    ultimoFim = re.lastIndex;
  }

  if (anterior) anterior.texto = semTags(artigo.slice(ultimoFim));
  else partes.push({ ancora: '', secao: '', texto: semTags(artigo) });

  return partes.filter((parte) => parte.texto || parte.secao);
}

const itens = [];
const ausentes = [];

for (const pagina of paginasDoMenu()) {
  const caminho = caminhoDaPagina(pagina.id);
  if (!existsSync(caminho)) {
    ausentes.push(pagina.id);
    continue;
  }

  const artigo = artigoDe(readFileSync(caminho, 'utf8'));
  for (const secao of secoesDe(artigo)) {
    itens.push({
      t: pagina.titulo,
      s: secao.secao,
      e: encurtar(secao.texto),
      p: pagina.id,
      a: secao.ancora,
    });
  }
}

const cabecalho = `/* Generated by scripts/docs-index.mjs. Do not edit by hand. */\n`;
writeFileSync(SAIDA, `${cabecalho}window.VOODOO_DOCS_BUSCA = ${JSON.stringify(itens)};\n`, 'utf8');

const kb = (Buffer.byteLength(readFileSync(SAIDA)) / 1024).toFixed(1);
console.log(`search index: ${itens.length} sections from ${paginasDoMenu().length} pages, ${kb} KB`);
if (ausentes.length) console.log(`missing pages: ${ausentes.join(' ')}`);

const arquivos = [];
for (const pasta of ['', 'guia', 'referencia']) {
  const dir = join(DOCS, pasta);
  for (const nome of readdirSync(dir)) {
    if (nome.endsWith('.html')) {
      arquivos.push((pasta ? `${pasta}/` : '') + nome.replace(/\.html$/, '').replace(/^index$/, ''));
    }
  }
}
const orfas = arquivos.filter((a) => !paginasDoMenu().some((p) => p.id === a));
if (orfas.length) console.log(`pages outside menu: ${orfas.join(' ')}`);
